import { z } from 'zod';

const optionalString = z.string().nullable().optional();
const percentage = z.number().finite().min(0).max(1);
const nonNegative = z.number().finite().nonnegative();

export const adminSettingsSchema = z.object({
  p2pFeePct: percentage,
  bankMargin: percentage,
  thirdPartyMargin: percentage,
  vendorShareUnder1k: percentage,
  vendorShareOver1k: percentage,
  tierThreshold: nonNegative,
  vendorMinCollateral: nonNegative,
  baseExitFeePct: percentage,
  fiatWithdrawalFeePct: percentage,
  cryptoWithdrawalFeePct: percentage,
  cryptoPlatformFeePct: percentage,
  withdrawalFeeByRiskTier: z.record(z.string(), nonNegative),
  feeByPaymentMethod: z.record(z.string(), nonNegative),
  supportedPaymentMethods: z.array(z.string()),
  gasFeeTrc20: nonNegative,
  gasFeeErc20: nonNegative,
  gasFeeBep20: nonNegative,
  autoPayoutEnabled: z.boolean(),
  autoPayoutThresholdUsdc: nonNegative,
  autoPayoutMaxAmountUsdc: nonNegative,
  autoPayoutIntervalMs: z.number().int().nonnegative(),
  liveUsdToGhs: z.number().finite().positive(),
  liveRetailRate: z.number().finite().positive().nullable().optional(),
  liveCorporateRate: z.number().finite().positive().nullable().optional(),
  liveRateSource: z.string(),
  lastRateSync: optionalString,
  minAppVersion: z.string(),
  forceUpdateUrl: z.string(),
  updateMessage: z.string(),
  susuProfitPct: percentage,
  smartEscrowFeePct: percentage,
  escrowDraftExpiryHours: nonNegative,
  escrowFundedExpiryDays: nonNegative,
}).passthrough();

export const adminSettingsResponseSchema = z.object({
  success: z.literal(true),
  settings: adminSettingsSchema,
}).passthrough();

export const adminSettingsUpdateSchema = z.object({
  p2pFeePct: percentage.optional(),
  bankMargin: percentage.optional(),
  thirdPartyMargin: percentage.optional(),
  vendorShareUnder1k: percentage.optional(),
  vendorShareOver1k: percentage.optional(),
  tierThreshold: nonNegative.optional(),
  vendorMinCollateral: nonNegative.optional(),
  baseExitFeePct: percentage.optional(),
  fiatWithdrawalFeePct: percentage.optional(),
  cryptoWithdrawalFeePct: percentage.optional(),
  cryptoPlatformFeePct: percentage.optional(),
  withdrawalFeeByRiskTier: z.record(z.string(), nonNegative).optional(),
  feeByPaymentMethod: z.record(z.string(), nonNegative).optional(),
  supportedPaymentMethods: z.array(z.string()).optional(),
  gasFeeTrc20: nonNegative.optional(),
  gasFeeErc20: nonNegative.optional(),
  gasFeeBep20: nonNegative.optional(),
  autoPayoutEnabled: z.boolean().optional(),
  autoPayoutThresholdUsdc: nonNegative.optional(),
  autoPayoutMaxAmountUsdc: nonNegative.optional(),
  autoPayoutIntervalMs: z.number().int().nonnegative().optional(),
  liveUsdToGhs: z.number().finite().positive().optional(),
  liveRetailRate: z.number().finite().positive().optional(),
  liveCorporateRate: z.number().finite().positive().optional(),
  liveRateSource: z.string().optional(),
  lastRateSync: z.string().nullable().optional(),
  minAppVersion: z.string().optional(),
  forceUpdateUrl: z.string().optional(),
  updateMessage: z.string().optional(),
  susuProfitPct: percentage.optional(),
  smartEscrowFeePct: percentage.optional(),
  escrowDraftExpiryHours: nonNegative.optional(),
  escrowFundedExpiryDays: nonNegative.optional(),
}).strict();
