// tailwind.config.js — Forge design system bridge (admin portal)
// Phase 1: az-* and shadcn aliases kept temporarily for backward compat.
// They map to Forge tokens and will be removed in Phase 8 (Purge).
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // ── Forge tokens (the real system) ──
        bg:            'var(--f-bg)',
        surface:       'var(--f-surface)',
        'surface-sunken':'var(--f-surface-sunken)',
        'surface-raised':'var(--f-surface-raised)',
        rail:          'var(--f-rail)',
        ink:           'var(--f-text)',
        'ink-2':       'var(--f-text-2)',
        'ink-3':       'var(--f-text-3)',
        'ink-inv':     'var(--f-text-inv)',
        line:          'var(--f-line)',
        'line-strong': 'var(--f-line-strong)',
        'line-contrast':'var(--f-line-contrast)',
        accent:        'var(--f-accent)',
        'accent-text': 'var(--f-accent-text)',
        tint:          'var(--f-tint-color)',
        ok:'var(--f-ok)','ok-bg':'var(--f-ok-bg)',
        warn:'var(--f-warn)','warn-bg':'var(--f-warn-bg)',
        bad:'var(--f-bad)','bad-bg':'var(--f-bad-bg)',
        info:'var(--f-info)','info-bg':'var(--f-info-bg)',

        // ── Legacy az-* aliases (removed in Phase 8) ──
        'az-bg':       'var(--f-bg)',
        'az-sidebar':  'var(--f-surface)',
        'az-surface-0':'var(--f-surface)',
        'az-surface-1':'var(--f-surface-sunken)',
        'az-surface-2':'var(--f-surface-raised)',
        'az-border':   'var(--f-line)',
        'az-border-bright':'var(--f-line-strong)',
        'az-emerald':  'var(--f-tint-color)',
        'az-text':     'var(--f-text)',
        'az-text-primary':'var(--f-text)',
        'az-text-secondary':'var(--f-text-2)',
        'az-text-muted':'var(--f-text-3)',
        'az-black':    'var(--f-ink-900)',
        'az-card':     'var(--f-surface)',
        'az-blue':     'var(--f-info)',
        'az-purple':   'var(--f-tint-color)',
        'az-amber':    'var(--f-warn)',
        'az-red':      'var(--f-bad)',
        'az-teal':     'var(--f-info)',
        'az-info':     'var(--f-info)',
        'az-violet':   'var(--f-tint-color)',
        'az-success':  'var(--f-ok)',
        'az-danger':   'var(--f-bad)',
        'az-warning':  'var(--f-warn)',

        // shadcn/ui compat (mapped to Forge)
        background: 'var(--f-bg)',
        foreground:  'var(--f-text)',
        card: { DEFAULT:'var(--f-surface)', foreground:'var(--f-text)' },
        popover: { DEFAULT:'var(--f-surface)', foreground:'var(--f-text)' },
        primary: { DEFAULT:'var(--f-accent)', foreground:'var(--f-accent-text)' },
        secondary: { DEFAULT:'var(--f-surface-sunken)', foreground:'var(--f-text-2)' },
        muted: { DEFAULT:'var(--f-surface-sunken)', foreground:'var(--f-text-3)' },
        accent: { DEFAULT:'var(--f-surface-sunken)', foreground:'var(--f-text)' },
        destructive: { DEFAULT:'var(--f-bad)', foreground:'#fff' },
        border: 'var(--f-line)',
        input:  'var(--f-line-strong)',
        ring:   'var(--f-line-contrast)',
        chart: {
          '1':'var(--f-tint-color)', '2':'var(--f-ink-400)',
          '3':'var(--f-line-strong)', '4':'var(--f-info)', '5':'var(--f-warn)',
        },
        sidebar: {
          DEFAULT:'var(--f-surface)',
          foreground:'var(--f-text)',
          primary:'var(--f-accent)',
          'primary-foreground':'var(--f-accent-text)',
          accent:'var(--f-surface-sunken)',
          'accent-foreground':'var(--f-text)',
          border:'var(--f-line)',
          ring:'var(--f-line-contrast)',
        },
      },
      fontFamily: { sans:['Inter','ui-sans-serif','system-ui','sans-serif'],
                    mono:['JetBrains Mono','ui-monospace','monospace'] },
      fontSize: {
        xs:  ['11px',{lineHeight:'16px'}],
        sm:  ['12px',{lineHeight:'18px'}],
        base:['13px',{lineHeight:'19px'}],
        md:  ['13px',{lineHeight:'19px'}],
        lg:  ['15px',{lineHeight:'22px'}],
        xl:  ['19px',{lineHeight:'26px',letterSpacing:'-0.022em'}],
        '2xl':['24px',{lineHeight:'30px',letterSpacing:'-0.028em'}],
        '3xl':['30px',{lineHeight:'36px',letterSpacing:'-0.032em'}],
      },
      borderRadius: { DEFAULT:'6px', sm:'4px', md:'6px', lg:'8px', xl:'12px', '2xl':'16px' },
      spacing: { row:'32px','row-sm':'26px','row-lg':'38px',
                 rail:'52px', panel:'212px', topbar:'48px' },
      boxShadow: {
        flush:'var(--f-d-flush)', d1:'var(--f-d-1)',
        d2:'var(--f-d-2)', d3:'var(--f-d-3)', bevel:'var(--f-bevel)',
        'az-xs':'var(--f-d-flush)', 'az-sm':'var(--f-d-1)',
        'az-md':'var(--f-d-2)', 'az-lg':'var(--f-d-3)',
      },
      backgroundImage: {
        'az-gradient':'linear-gradient(135deg, color-mix(in oklab, var(--f-tint-color) 12%, transparent) 0%, color-mix(in oklab, var(--f-info) 12%, transparent) 100%)',
      },
      transitionTimingFunction: { out:'var(--f-e-out)', io:'var(--f-e-io)' },
    },
  },
  plugins: [],
}
